---
- hosts: omapp

  tasks:
  - name: Check Online Mediation Version
    slurp:
     src: /home/see/nginrun/lib/ocg_version.dat
    register: omver

  - name: Check ONIP Version
    shell: /home/see/nginrun/bin/bodaf/gv
    register: gvver

  - local_action: copy content="{{ omver.content | b64decode }}" dest=".tmp/omver.txt"
  - local_action: copy content="{{ gvver }}" dest=".tmp/onip.txt"
