- hosts: raspberry

  tasks:
  - name: get users
    shell: tail /etc/passwd|cut -d':' -f1
    register: users
  - debug: var=users.stdout_lines
  #- debug: msg="{{ users.stderr }}"
  
  - name: get processes
    shell: "echo ps -fu {{ users.stdout_lines }}"
    #with_items:
    #- "{{ users }}"
    register: proc
  - debug: var=proc.stdout_lines




system:
---
- hosts: vendor1
  remote_user: sysomc

  tasks:
  - name: get users
    shell: tail /etc/passwd|cut -d':' -f1
    register: users
  - debug: var=users
  
  - name: get processes
    shell: ps -fu "{{ item }}"
    with_items:
    - "{{ users }}"
    register: proc
  - debug: var=proc
