---
- hosts: ccs
  remote_user: sysomc

tasks:
- name: get users
  shell: tail /etc/passwd|cut -d':' -f1
  register: users
- debug: var=users

- name: get processes
  shell: ps -fu "{{ item }}"
  with_items:
  - "{{ users }}"
  register: proc
- debug: var=proc



system:
---
- hosts: vendor1
  remote_user: sysomc

  tasks:
  - name: get users
    shell: tail /etc/passwd|cut -d':' -f1
    register: users
  - debug: var=users
  
  - name: get processes
    shell: ps -fu "{{ item }}"
    with_items:
    - "{{ users }}"
    register: proc
  - debug: var=proc
